### ISSUE TITLE
[Build] Swift Lint를 적용합니다.

### ISSUE THREAD

**Issue by dahae0320** [GitSpacer/GitSpace#10]
### 📝 작업 목적

- 코드 컨벤션을 위해 Swift Lint를 적용합니다.
- [Airbnb Swift Style Guide](https://github.com/airbnb/swift)를 따릅니다.
- 프로젝트에 라이브러리로 설치하지 않고 local에 설치하여 의존성을 낮춥니다.

---

### 🛠️ Tasks

* [x] local에 swift lint 설치
   * `brew install swiftlint`
* [x] 프로젝트에 Swift Lint 세팅
* [ ] SwiftLint 도큐먼트 읽고 필요한 내용 설정하기
