### ISSUE TITLE
[Feat] Firebase 추상화 서비스 클라이언트를 구현합니다.

### ISSUE THREAD

**Issue by wontaeyoung** [GitSpacer/GitSpace#21]
### 📝 작업 목적

GitSpace에서는 Github API / Firebase 크게 두 개의 서버로부터 데이터를 주고받습니다.

Github Service는 추상화 클라이언트가 구현되어있어서 각 도메인에서 동일한 방식으로 네트워크 요청을 수행하고 있지만, Firebase는 별도의 추상화 서비스가 구현되어있지 않아서 도메인에서 서로 다른 방법으로 수행하고 있습니다.

Firebase 요청 방식을 통일하고 유지보수 효율을 높이기 위해 Firebase 추상화 서비스 클라이언트를 구현합니다.

---

### 🛠️ Tasks

* [x] GitSpace Firestore Model 구조 파악
* [x] private 메서드 및 기반 타입 작성
* [x] CRUD API 구현
* [x] 테스트 검증
