### ISSUE TITLE
[Feat] Star Repository UI(메인뷰) 구현

### ISSUE THREAD

**Issue by dahae0320** [GitSpacer/GitSpace#22]
### 📝 작업 목적

GitSpace의 메인 화면인 Star 탭의 뷰를 구현합니다. 데이터는 APIController가 완성되기 전까지 더미로 사용하고, GSCanvas와 GSButton을 이용해서 뷰를 구성하도록 하자.
이때 무한 스크롤으로 모든 Star Repository를 가져오도록 하자.

---

### 🛠️ Tasks

* [x] TCA 아키텍쳐에서 뷰는 어떻게 구성하는가 -> 동일
* [x] GSStarFeature 프레임워크 추가, 해당 폴더에서 작업
* [x] Star 탭의 기본 화면인 StarRepositoryView 구현
    * [x] 내부 구성 컴포넌트화
