### ISSUE TITLE
[Feat] GitHub API 코드 마이그레이션

### ISSUE THREAD

**Issue by jekyun-park** [GitSpacer/GitSpace#24]
### 📝 작업 목적

이슈 #21 작업 마무리 이후, Network 모듈에 기존 GitHub API 관련 코드를 마이그레이션합니다.
목표는 Network 모듈 아래에 GitHub Service / Firebase Service 를 함께 두어 네트워크 코드를 모듈 단위로 함께 관리하는 것입니다.

---

### 🛠️ Tasks

* [x] #21 이슈 파악 및 코드 리뷰
* [x] GitHub API 코드 점검 및 개선점 파악
* [x] Network 모듈에 GitHub API 코드 병합
